// Developer Muffler
const booksData = [
  { id: 1, title: "Старинная Книга", author: "Неизвестен", price: 445, cover: "image/book/book1.png" },
  { id: 2, title: "Толстой, Рассказы и сказки", author: "Лев Толстой", price: 625, cover: "image/book/book2.png" },
  { id: 3, title: "Преступление и наказание", author: "Федор Достоевский", price: 375, cover: "image/book/book3.png" },
  { id: 4, title: "Гарри Поттер", author: "Джоан Роулинг", price: 345, cover: "image/book/book4.png" },
  { id: 5, title: "Мастер и Маргарита", author: "Михаил Булгаков", price: 750, cover: "image/book/book5.png" },
  { id: 6, title: "Дорога", author: "Кормак Маккарти", price: 550, cover: "image/book/book6.png" },
  { id: 7, title: "Приключения Шерлока Холмса", author: "Артур Конан Дойл", price: 475, cover: "image/book/book7.png" },
  { id: 8, title: "Мирный Воин", author: "Дэн Миллман", price: 410, cover: "image/book/book8.png" },
  { id: 9, title: "Теория Пустоты", author: "Стивен Хокинг", price: 360, cover: "image/book/book9.png" },
  { id: 10, title: "Счастливая жизнь Веры Тапкиной", author: "Вера Тапкина", price: 340, cover: "image/book/book10.png" },
  { id: 11, title: "365 Дней Самодисциплины", author: "Джон Смит", price: 575, cover: "image/book/book11.png" },
  { id: 12, title: "Магия Утра", author: "Хэл Элрод", price: 440, cover: "image/book/book12.png" },
  { id: 13, title: "Устала Уставать", author: "Мария Иванова", price: 675, cover: "image/book/book13.png" },
  { id: 14, title: "О успехе в жизни и бизнесе", author: "Роберт Кийосаки", price: 490, cover: "image/book/book14.png" },
  { id: 15, title: "Начало Великой Отечественной Войны", author: "Александр Анфилов", price: 325, cover: "image/book/book15.png" },
  { id: 16, title: "Яды", author: "Нил Брэдбери", price: 395, cover: "image/book/book16.png" },
  { id: 17, title: "Троцкий: Преданная революция", author: "Лев Троцкий", price: 460, cover: "image/book/book17.png" },
  { id: 18, title: "Правда о Чернобыле", author: "Владимир Губарев", price: 435, cover: "image/book/book18.png" },
  { id: 19, title: "Реальная История Штрафбатов", author: "Максим Калинин", price: 725, cover: "image/book/book19.png" },
  { id: 20, title: "Владимир Путин", author: "Александр Мясников", price: 280, cover: "image/book/book20.png" },
  { id: 21, title: "Войны и Сражения", author: "Олег Соколов", price: 525, cover: "image/book/book21.png" },
  { id: 22, title: "2020 World Of War", author: "Сол Корниш", price: 390, cover: "image/book/book22.png" },
  { id: 23, title: "At War on the Gothic Line", author: "Кристиан Дженнингс", price: 625, cover: "image/book/book23.png" },
  { id: 24, title: "The Time Traveller's Handbook", author: "Джеймс Ванн", price: 445, cover: "image/book/book24.png" },
  { id: 25, title: "Doctor Who", author: "Рассел Т. Дэвис", price: 320, cover: "image/book/book25.png" },
  { id: 26, title: "Slugfest: Marvel and DC", author: "Рид Такер", price: 490, cover: "image/book/book26.png" },
  { id: 27, title: "Father and Son", author: "Ларри Браун", price: 360, cover: "image/book/book27.png" },
  { id: 28, title: "The Disappearance of Emile Zola", author: "Михаил Розен", price: 550, cover: "image/book/book28.png" }
];

const catalogData = [
  { id: 1, title: "Астрономия", author: "Эдвин Хаббл", originalPrice: 1780, price: 890, cover: "image/catalog/catalog-book1.png" },
  { id: 2, title: "Черные Дыры и Молодые Вселенные", author: "Стивен Хокинг", originalPrice: 1580, price: 790, cover: "image/catalog/catalog-book2.png" },
  { id: 3, title: "Денискины Рассказы", author: "Виктор Драгунский", originalPrice: 1980, price: 990, cover: "image/catalog/catalog-book3.png" },
  { id: 4, title: "Дары Волхвов", author: "Олег Генри", originalPrice: 1380, price: 690, cover: "image/catalog/catalog-book4.png" },
  { id: 5, title: "Семь Чудес Света", author: "Юлия Школьник", originalPrice: 1700, price: 850, cover: "image/catalog/catalog-book5.png" },
  { id: 6, title: "Аленушкины Сказки", author: "Дмитрий Мамин-Сибиряк", originalPrice: 2400, price: 1200, cover: "image/catalog/catalog-book6.png" },
  { id: 7, title: "Черти Что", author: "Дмитрий Матвеев", originalPrice: 1500, price: 750, cover: "image/catalog/catalog-book7.png" },
  { id: 8, title: "Слово Пацана", author: "Роберт Гараев", originalPrice: 1640, price: 820, cover: "image/catalog/catalog-book8.png" },
  { id: 9, title: "Жихарка", author: "Гора Самоцветов", originalPrice: 1360, price: 680, cover: "image/catalog/catalog-book9.png" },
  { id: 10, title: "Крокодил Гена и его Друзья", author: "Э. Успенский", originalPrice: 1900, price: 950, cover: "image/catalog/catalog-book10.png" },
  { id: 11, title: "Илья Ильф", author: "Ильф Илья Арнольдович", originalPrice: 2500, price: 1250, cover: "image/catalog/catalog-book11.png" },
  { id: 12, title: "Счастливые люди читают книжки и пьют кофе", author: "Аньес Мартен-Люган", originalPrice: 1760, price: 880, cover: "image/catalog/catalog-book12.png" },
  { id: 13, title: "Мафин", author: "Энн Хогарт", originalPrice: 1840, price: 920, cover: "image/catalog/catalog-book13.png" },
  { id: 14, title: "Счастья с Книжкой", author: "Бьянка Питцорно", originalPrice: 1400, price: 700, cover: "image/catalog/catalog-book14.png" },
  { id: 15, title: "Фантастические Твари и где они обитают", author: "Дж.К. Роулинг", originalPrice: 1560, price: 780, cover: "image/catalog/catalog-book15.png" },
  { id: 16, title: "Приключение Тома Сойера", author: "Марк Твен", originalPrice: 1520, price: 760, cover: "image/catalog/catalog-book16.png" },
  { id: 17, title: "Незнайка на Луне", author: "Н. Носов", originalPrice: 1440, price: 720, cover: "image/catalog/catalog-book17.png" },
  { id: 18, title: "Инструкция к Жизни", author: "Ева Морозова", originalPrice: 1780, price: 890, cover: "image/catalog/catalog-book18.png" },
  { id: 19, title: "Маня Фишер", author: "Елизавета Бута", originalPrice: 1880, price: 940, cover: "image/catalog/catalog-book19.png" },
  { id: 20, title: "Окна Делириса", author: "Марина Ясинская", originalPrice: 1960, price: 980, cover: "image/catalog/catalog-book20.png" },
  { id: 21, title: "Твое Сердце Будет Разбито", author: "Анна Джейн", originalPrice: 2100, price: 1050, cover: "image/catalog/catalog-book21.png" },
  { id: 22, title: "Новая Жизнь", author: "Дмитрий Хара", originalPrice: 1760, price: 880, cover: "image/catalog/catalog-book22.png" },
  { id: 23, title: "Бегущий в Лабиринте", author: "Джеймс Дэшнер", originalPrice: 2300, price: 1150, cover: "image/catalog/catalog-book23.png" },
  { id: 24, title: "Год в Лесу", author: "Эмилия Озюбак", originalPrice: 1960, price: 980, cover: "image/catalog/catalog-book24.png" },
  { id: 25, title: "Истории из Простоквашино", author: "Э. Успенский", originalPrice: 2500, price: 1250, cover: "image/catalog/catalog-book25.png" },
  { id: 26, title: "История Старой Квартиры", author: "Литвина А.", originalPrice: 2100, price: 1050, cover: "image/catalog/catalog-book26.png" },
  { id: 27, title: "Ходящие в Ночи", author: "Алена Харитонова и Екатерина Казакова", originalPrice: 2300, price: 1150, cover: "image/catalog/catalog-book27.png" },
  { id: 28, title: "Говори Красиво и Уверенно", author: "Евгения Шестакова", originalPrice: 2700, price: 1350, cover: "image/catalog/catalog-book28.png" },
  { id: 29, title: "Дети Синего Фламинго", author: "Владислав Крапивин", originalPrice: 2400, price: 1200, cover: "image/catalog/catalog-book29.png" },
  { id: 30, title: "Тайна Мертвого Ректора", author: "Виктор Дашкевич", originalPrice: 2400, price: 1200, cover: "image/catalog/catalog-book30.png" },
  { id: 31, title: "Оттенки Моего Безумия", author: "Сабина Рейн", originalPrice: 2400, price: 1200, cover: "image/catalog/catalog-book31.png" },
  { id: 32, title: "Джейсон Стэтхем Большая Книга Цитат", author: "Не известен", originalPrice: 1780, price: 890, cover: "image/catalog/catalog-book32.png" },
  { id: 33, title: "Моя Вина", author: "Рон М.", originalPrice: 1840, price: 920, cover: "image/catalog/catalog-book33.png" },
  { id: 34, title: "Жизнь Взаймы, или У Неба Любимчиков Нет", author: "Эрих Мария", originalPrice: 1700, price: 850, cover: "image/catalog/catalog-book34.png" },
  { id: 35, title: "Чебурашка", author: "Маслова А.А.", originalPrice: 1960, price: 980, cover: "image/catalog/catalog-book35.png" },
  { id: 36, title: "Мой Театр", author: "Николай Цискаридзе", originalPrice: 1580, price: 790, cover: "image/catalog/catalog-book36.png" },
  { id: 37, title: "Токийский Гуль", author: "Суи Исида", originalPrice: 1760, price: 880, cover: "image/catalog/catalog-book37.png" },
  { id: 38, title: "История о Жизни, Смерти и Нейрохирургии", author: "Генри Марш", originalPrice: 1680, price: 840, cover: "image/catalog/catalog-book38.png" },
  { id: 39, title: "Четыре Соглашения", author: "Дон Мигель Руис", originalPrice: 1840, price: 920, cover: "image/catalog/catalog-book39.png" },
  { id: 40, title: "Письма Баламута", author: "Клайв Стейплз", originalPrice: 2100, price: 1050, cover: "image/catalog/catalog-book40.png" }
];

const newBooksData = [
  { id: 101, title: "Ведьмак. Последнее желание", author: "Анджей Сапковский", category: "fiction", price: 890, originalPrice: 1780, cover: "image/new/book1.png" },
  { id: 102, title: "Атомные привычки", author: "Джеймс Клир", category: "nonfiction", price: 750, originalPrice: 1500, cover: "image/new/book2.png" },
  { id: 103, title: "Дюна", author: "Фрэнк Герберт", category: "fiction", price: 990, originalPrice: 1980, cover: "image/new/book3.png" },
  { id: 104, title: "Искусство заботы о себе", author: "Андрей Миллиардов", category: "nonfiction", price: 650, originalPrice: 1300, cover: "image/new/book4.png" },
  { id: 105, title: "Маленький принц", author: "Антуан де Сент-Экзюпери", category: "children", price: 450, originalPrice: 900, cover: "image/new/book5.png" },
  { id: 106, title: "Думай медленно... решай быстро", author: "Даниэль Канеман", category: "business", price: 1250, originalPrice: 2500, cover: "image/new/book6.png" },
  { id: 107, title: "1984", author: "Джордж Оруэлл", category: "fiction", price: 550, originalPrice: 1100, cover: "image/new/book7.png" },
  { id: 108, title: "Гарри Поттер и философский камень", author: "Дж.К. Роулинг", category: "children", price: 690, originalPrice: 1380, cover: "image/new/book8.png" },
  { id: 109, title: "Стартап. Настольная книга", author: "Стив Бланк", category: "business", price: 1150, originalPrice: 2300, cover: "image/new/book9.png" },
  { id: 110, title: "Сила привычки", author: "Чарльз Дахигг", category: "nonfiction", price: 850, originalPrice: 1700, cover: "image/new/book10.png" },
  { id: 111, title: "Игра престолов", author: "Джордж Р.Р. Мартин", category: "fiction", price: 1450, originalPrice: 2900, cover: "image/new/book11.png" },
  { id: 112, title: "Эмоциональный интеллект", author: "Дэниел Гоулман", category: "business", price: 950, originalPrice: 1900, cover: "image/new/book12.png" }
];